name: on-demand self-hosted aws runner (with convenient aws defaults) for github actions
description: |
  github action for creation and registration of aws instances as gitjub actions self-hosted runners.
  this action is a fork of [machulav/ec2-github-runner](https://github.com/machulav/ec2-github-runner).
  it has been modified to:
  - support image (ami) search patterns and owners rather than a specific ami id. useful if, for example, the latest ubuntu image is required.
  - bootstrap the image by installing docker and git if they are not preinstalled.
  - support overriding user-data when custom dependencies need to be preinstalled.
  - setting of the aws region with the aws-region input rather than an environment variable.
  - support use of the default subnet and security group for the vpc/az instead of requiring an explicit security group and subnet.
  - support use of spot or scheduled instances as opposed to only scheduled instances.
  - support setting the volume (disk) size so that more than the default 8gb is available to jobs.
author: rob thijssen
branding:
  icon: cloud-lightning
  color: purple
inputs:
  mode:
    description: >-
      specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      github personal access token with the 'repo' scope assigned.
    required: true
  aws-access-key-id:
    description: >-
      aws access key id (credential account).
    required: true
  aws-secret-access-key:
    description: >-
      aws secret access key (credential secret).
    required: true
  aws-region:
    description: >-
      aws region. the runner instance will be launched in this region.
    required: true
  aws-image-id:
    description: >-
      aws image id (ami). the runner instance will be launched from this image.
      either aws-image-id or aws-image-search-pattern is required if the 'start' mode is used.
    required: false
  aws-image-search-pattern:
    description: >-
      aws image (ami) search pattern. the runner instance will be launched from the latest image whose name matches this search pattern.
      either aws-image-id or aws-image-search-pattern is required if the 'start' mode is used.
    default: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
    required: false
  aws-image-search-owners:
    description: >-
      aws image (ami) search owners. the runner instance will be launched from the latest image whose name matches aws-image-search-pattern and whose owner is included in this list.
      this must be a stringified array of strings, for example,
      to use images owned/created by amazon: '["amazon"]',
      to use images owned/created by a specific aws account id: '["123456789"]'.
    default: '["099720109477"]' # canonical
    required: false
  aws-instance-user-data:
    description: >-
      aws instance user data. this field should only be set if overriding default user-data is required.
      for example to install action specific dependencies. if set, the user-data must include commands to install, configure and run github-action-runner as the default user-data does.
    required: false
  # aws-instance-packages:
  #   description: >-
  #     packages to pre-install at instance bootstrap.
  #   default: '["build-essential", "clang", "cmake", "containerd.io", "docker-ce", "docker-ce-cli", "git", "jq"]'
  #   required: false
  aws-instance-username:
    description: >-
      aws instance username. this field should be set if overriding default username is required.
    default: runner
    required: false
  aws-instance-ssh-public-key:
    description: >-
      aws instance ssh public key. this field should be set if ssh connections to the runner instance are required.
    required: false
  aws-instance-type:
    description: >-
      aws instance type.
      this input is required if you use the 'start' mode.
    required: false
  aws-instance-lifecycle:
    description: >-
      aws instance lifecycle.
      possible values:
      - spot: cheaper instances that may disappear mid-task
      - scheduled: normal instances
    default: scheduled
    required: false
  aws-instance-root-volume-name:
    description: >-
      aws instance root volume name
      it is usually best to leave this unset since its value is often specific to each ami. its value will be looked up when the image is found.
      typical root volume names:
      - /dev/sda1 (ubuntu)
      - /dev/xvda
    default: /dev/sda1
    required: false
  aws-instance-root-volume-size:
    description: >-
      aws instance root volume size in gigabytes
    default: 8
    required: false
  aws-subnet-id:
    description: >-
      aws subnet id. the subnet should belong to the same vpc as the specified security group.
    required: false
  aws-security-group-id:
    description: >-
      aws security group id.
      the security group should belong to the same vpc as the specified subnet.
      the runner doesn't require any inbound traffic. however, outbound traffic should be allowed.
    required: false
  runner-label:
    description: >-
      name of the unique label assigned to the runner.
      the label is used to remove the runner from github when the runner is not needed anymore.
      this input is required if you use the 'stop' mode.
    required: false
  runner-install-dir:
    description: >-
      the path to the github-action-runner installation
    default: /home/runner/runners/2.280.1
    required: false
  runner-arch:
    description: >-
      the architecture of the github action runner installer
    default: x64
    required: false
  runner-version:
    description: >-
      the version of the github action runner installer
    default: '2.280.1'
    required: false
  node-version:
    description: >-
      the version of nvm to install
    default: '16.3.0'
    required: false
  npm-version:
    description: >-
      the version of nvm to install
    default: '7.20.6'
    required: false
  nvm-version:
    description: >-
      the version of nvm to install
    default: '0.38.0'
    required: false
  aws-instance-id:
    description: >-
      aws instance id of the created runner.
      the id is used to terminate the aws instance when the runner is not needed anymore.
      this input is required if you use the 'stop' mode.
    required: false
  aws-iam-role-name:
    description: >-
      iam role name to attach to the created aws instance.
      this requires additional permissions on the aws role used to launch instances.
    required: false
  aws-resource-tags:
    description: >-
      tags to attach to the launched aws instance and volume.
      this must be a stringified array of aws tag objects, with both key and value fields,
      for example: '[{"key": "tagkey1", "value": "tagvalue1"}, {"key": "tagkey2", "value": "tagvalue2"}]'
    required: false
outputs:
  runner-label:
    description: >-
      name of the unique label assigned to the runner.
      the label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from github when it is not needed anymore.
  aws-region:
    description: >-
      aws region of the created runner.
      the region is used to terminate the aws instance when the runner is not needed anymore.
  aws-instance-id:
    description: >-
      aws instance id of the created runner.
      the id is used to terminate the aws instance when the runner is not needed anymore.
runs:
  using: node12
  main: ./dist/index.js
