on:
  push:
    branches:
      - main

name: package

jobs:
  package:
    name: Package distribution files
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: main
      -
        name: install packages
        run: npm ci
      -
        name: lint
        run: npm run lint
      -
        name: package
        run: npm run package
      -
        name: commit and push
        run: |
          git config --global user.name "github actions"
          git add dist/
          git commit -m "update dist" || echo "no changes to commit"
          git push origin main
